services:
  theatre-log-app:
    image: dutoitro/theatre-log-app:latest
    build: .
    container_name: theatre-log-app
    ports:
      - "3838:3838"
    volumes:
      - data:/srv/shiny-server/data
    restart: unless-stopped

volumes:
  data:

